const colleges = [
    "ASM Group",
    "Chennai Institute of Technology",
    "Chitkara University",
    "DES University",
    "GLA University",
    "IIIT Delhi",
    "IIMT",
    "IIT Bhilai",
    "IIT BHU (Varanasi)",
    "IIT Bombay",
    "IIT Delhi",
    "IIT Dhanbad (ISM)",
    "IIT Dharwad",
    "IIT Gandhinagar",
    "IIT Goa",
    "IIT Guwahati",
    "IIT Hyderabad",
    "IIT Indore",
    "IIT Jammu",
    "IIT Jodhpur",
    "IIT Kanpur",
    "IIT Kharagpur",
    "IIT Madras",
    "IIT Mandi",
    "IIT Palakkad",
    "IIT Patna",
    "IIT Roorkee",
    "IIT Ropar",
    "IIT Tirupati",
    "IMT",
    "KIIT University",
    "KIT",
    "KPR College of Arts, Science & Research, Coimbatore",
    "Lovely Professional University",
    "MIT ADT University",
    "MNNIT Allahabad",
    "NIT Agartala",
    "NIT Andhra Pradesh",
    "NIT Arunachal Pradesh",
    "NIT Bhopal",
    "NIT Calicut",
    "NIT Delhi",
    "NIT Durgapur",
    "NIT Goa",
    "NIT Hamirpur",
    "NIT Jaipur",
    "NIT Jalandhar",
    "NIT Jamshedpur",
    "NIT Karnataka",
    "NIT Kerala",
    "NIT Kurukshetra",
    "NIT Manipur",
    "NIT Meghalaya",
    "NIT Mizoram",
    "NIT Nagaland",
    "NIT Patna",
    "NIT Puducherry",
    "NIT Raipur",
    "NIT Rourkela",
    "NIT Sikkim",
    "NIT Silchar",
    "NIT Srinagar",
    "NIT Surat",
    "NIT Trichy",
    "NIT Uttarakhand",
    "NIT Warangal",
    "NMIMS",
    "PES University",
    "School of Inspired Leadership (SOIL)",
    "Sri Eshwar College",
    "VNIT Nagpur"
]

export default colleges;